// Mocks generated by Mockito 5.1.0 from annotations
// in search/test/domain/usecase/search_tv_series_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:core/domain/entities/tv_series.dart' as _i6;
import 'package:core/domain/entities/tv_series_detail.dart' as _i7;
import 'package:core/domain/repositories/tv_series_repository.dart' as _i3;
import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i3.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>> getOnAirTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getOnAirTvSeries, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>
      getPopularTvSeries() =>
          (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
              as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>
      getTopRatedTvSeries() =>
          (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
              as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>> searhcTvSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searhcTvSeries, [query]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvSeriesDetail>> getDetailTvSeries(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTvSeries, [id]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i7.TvSeriesDetail>>.value(
                      _FakeEither_0<_i5.Failure, _i7.TvSeriesDetail>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.TvSeriesDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>
      getTvSeriesRecomendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getTvSeriesRecomendations, [id]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistTvSeries(
          _i7.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
              Invocation.method(#saveWatchlistTvSeries, [tvSeriesDetail]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlistTvSeries(
          _i7.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
              Invocation.method(#removeWatchlistTvSeries, [tvSeriesDetail]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isTvSeriesAddedToWathclist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isTvSeriesAddedToWathclist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>
      getTvSeriesWatchlist() =>
          (super.noSuchMethod(Invocation.method(#getTvSeriesWatchlist, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
              as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
}
